### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by ajeema** [harshilpatel99/image_superResolution#1]
Running this code I came across the following error:

`33
plt.imshow(img_array[100])
---------------------------------------------------------------------------

IndexError  Traceback (most recent call last)
<ipython-input-33-487dac4fd3b0> in <module>
----> 1 plt.imshow(img_array[100])
IndexError: list index out of range
`

I get this running it locally in PyCharm as well as online on Colab. Any ideas why?

**Comment by harshilpatel99** [comment]
Hi!
I verified my code, its working fine on my side. 

Verify following things on your side:
- After reading file paths with glob, check the length of face_images list. It should be around 13233.
- After loading and processing images, do verify the length of img_array. It should be same as of face_images.
I think after checking this it should work.

Or if you are getting stuck at multiprocessing approach, you can go with the naive method by removing Pool and map lines and add this:

img_array = []
for i in face_images:
     print(face_images.index(i))
     img_array.append(read(i))

**Comment by harshilpatel99** [comment]
Hi!
I verified my code, its working fine on my side.

Verify following things on your side:

After reading file paths with glob, check the length of face_images list. It should be around 13233.
After loading and processing images, do verify the length of img_array. It should be same as of face_images.
I think after checking this it should work.
Or if you are getting stuck at multiprocessing approach, you can go with the naive method by removing Pool and map lines and add this:

img_array = []
for i in face_images:
print(face_images.index(i))
img_array.append(read(i))
